dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
networks:
  default: development
  development:
    verify: False
  ganache-local:
    verify: False
  bsc:
    eth_usd_price_feed: "0x2514895c72f50D8bd4B4F9b1110F0D6bD2c97526"
    vrf_coordinator: "0x747973a5A2a4Ae1D3a8fDF5479f1514F65Db9C31"
    link_token: "0x404460C6A5EdE2D891e8297795264fDe62ADBB75"
    keyhash: "0xc251acd21ec4fb7f31bb8868288bfdbaeb4fbfec2df3735ddbd4f7dc8d60103c"
    fee: 200000000000000000
    verify: True
  bsc-test:
    eth_usd_price_feed: "0x2514895c72f50D8bd4B4F9b1110F0D6bD2c97526"
    verify: True
  rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    eth_usd_price_feed:  "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}

  # to launch ganache-cli -m "$(cat .secret)"